name: Deploy

on:
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3
      #   with:
      #     version: 8

      - name: Install Bun
        uses: oven-sh/setup-bun@v1


      - name: Install dependencies
        run: bun install

      - name: build
        run: |
          bun run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          # this should match the `pages` option in your adapter-static options
          name: build
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
    - name: copy file via ssh
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "."
        target: /var/www/html/portfolioV2